[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '''=[SMODS Multiplayer "ui/game.lua"]'''
pattern = """asdasdasdsdMP.ACTIONS.fail_round(G.GAME.current_round.hands_played)"""
position = "before"
payload = """AKYRS.end_round_event()"""
overwrite = true
match_indent = true

[[patches]]
[patches.pattern]
target = '''functions/state_events.lua'''
pattern = """        G.GAME.blind.in_blind = false"""
position = "before"
payload = """AKYRS.end_round_event()"""
overwrite = true
match_indent = true
