[manifest]
version = "1.2"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = """       elseif _c.name == "The World" then loc_vars = {cfg.max_highlighted, localize(cfg.suit_conv, 'suits_plural'), colours = {G.C.SUITS[cfg.suit_conv]}}
       end
       localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}"""
position = "after"
payload = """    
elseif _c.set == 'AikoyoriExtraBases' then
    if card and card.is_null and (card.ability.set == "Enhanced" or card.ability.set == "Default") then
        local gend = false
        if (G.GAME.akyrs_letters_mult_enabled) then
            localize{type = 'descriptions', key = "lettersMult", set = _c.set, vars = _c.vars or loc_vars}
            gend = true
        end
        if (G.GAME.akyrs_letters_xmult_enabled) then
            localize{type = 'descriptions', key = "lettersXMult", set = _c.set, vars = _c.vars or loc_vars}
            gend = true
        end
        if((_c.vars or loc_vars)[4]) then
            localize{type = 'descriptions', key = "letterCardFrequency", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        end
        if not gend then
            full_UI_table.name = localize{type = 'name', set = _c.set, nodes = full_UI_table.name,  key = key or "letters", vars = _c.vars or loc_vars}
        end
        localize{type = 'other', key = 'null_card', nodes = desc_nodes, vars = _c.vars or loc_vars}
    else
        if _c.key and string.sub(_c.key, -1) then
            local last_letter = string.lower(string.sub(_c.key, -1))
            local key = "letters"
            if(AKYRS.non_letter_symbols_reverse[last_letter]) then
                key = "symbols"
            end
            if(tonumber(last_letter)) then
                key = "numbers"
            end
            localize{type = 'descriptions', key = key , set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        else 
            localize{type = 'descriptions', key = "null_card", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        end
        
        if(G.GAME.akyrs_letters_mult_enabled or G.GAME.akyrs_letters_xmult_enabled) then
            if(G.GAME.akyrs_letters_mult_enabled) then
                localize{type = 'descriptions', key = "lettersMult", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
            end
            
            if(G.GAME.akyrs_letters_xmult_enabled) then
                localize{type = 'descriptions', key = "lettersXMult", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
            end
        end
        if((_c.vars or loc_vars)[4]) then
            localize{type = 'descriptions', key = "letterCardFrequency", set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
        end
    end
elseif _c.set == 'DescriptionDummy' then
    localize{type = 'descriptions', key = _c.key, set = _c.set, nodes = desc_nodes, vars = _c.vars or loc_vars}
"""
overwrite = true
match_indent = true

